# Batch Normalization vs Layer Normalization

## Objective

The objective of this experiment is to understand how Batch Normalization and Layer Normalization normalize input data and improve deep learning model training using TensorFlow.

In [1]:
import numpy as np
import tensorflow as tf

# Make the output easier to read
np.set_printoptions(precision=3, suppress=True)

In [2]:
# Generate random data
np.random.seed(42)

data = np.random.randint(10, 100, size=(5,4)).astype(np.float32)

print("Original Input:")
print(data)

Original Input:
[[61. 24. 81. 70.]
 [30. 92. 96. 84.]
 [84. 97. 33. 12.]
 [31. 62. 11. 97.]
 [39. 47. 11. 73.]]


In [3]:
batch_norm = tf.keras.layers.BatchNormalization()

batch_output = batch_norm(data, training=True)

print("Batch Normalization Output:")
print(batch_output.numpy())

Batch Normalization Output:
[[ 0.578 -1.472  0.971  0.096]
 [-0.915  1.006  1.393  0.576]
 [ 1.686  1.188 -0.376 -1.891]
 [-0.867 -0.087 -0.994  1.021]
 [-0.482 -0.634 -0.994  0.199]]


In [4]:
layer_norm = tf.keras.layers.LayerNormalization()

layer_output = layer_norm(data)

print("Layer Normalization Output:")
print(layer_output.numpy())

Layer Normalization Output:
[[ 0.093 -1.635  1.027  0.514]
 [-1.709  0.62   0.77   0.319]
 [ 0.783  1.154 -0.669 -1.268]
 [-0.592  0.361 -1.206  1.437]
 [-0.158  0.204 -1.425  1.38 ]]


In [5]:
print("="*50)

print("Original Input")
print(data)

print("\nBatch Normalization")
print(batch_output.numpy())

print("\nLayer Normalization")
print(layer_output.numpy())

Original Input
[[61. 24. 81. 70.]
 [30. 92. 96. 84.]
 [84. 97. 33. 12.]
 [31. 62. 11. 97.]
 [39. 47. 11. 73.]]

Batch Normalization
[[ 0.578 -1.472  0.971  0.096]
 [-0.915  1.006  1.393  0.576]
 [ 1.686  1.188 -0.376 -1.891]
 [-0.867 -0.087 -0.994  1.021]
 [-0.482 -0.634 -0.994  0.199]]

Layer Normalization
[[ 0.093 -1.635  1.027  0.514]
 [-1.709  0.62   0.77   0.319]
 [ 0.783  1.154 -0.669 -1.268]
 [-0.592  0.361 -1.206  1.437]
 [-0.158  0.204 -1.425  1.38 ]]


## Comparison

### Batch Normalization
Batch Normalization normalizes the input using the mean and variance of the entire batch of samples. It helps speed up training, stabilizes learning, and reduces internal covariate shift.

### Layer Normalization
Layer Normalization normalizes the features of each individual sample independently. It works well even when the batch size is small.

### Difference
Batch Normalization computes statistics across the batch, whereas Layer Normalization computes statistics across the features of each individual sample.